### ISSUE TITLE
CKE Texteditor removes tags or throws javascript error

### ISSUE THREAD

**Issue by Quehnie** [sulu-io/sulu#1041]
If i add some Code like:

![bildschirmfoto 2015-04-28 um 14 01 52](https://cloud.githubusercontent.com/assets/8446502/7369179/d7b55fbc-edaf-11e4-9449-9b867895aab3.png)

it removes the span tags. p, em and strong tags are not removed. Maybe default?

And if i use a div container it totally dies and throws a js error:

![bildschirmfoto 2015-04-28 um 14 02 39](https://cloud.githubusercontent.com/assets/8446502/7369175/cedfc8b4-edaf-11e4-9eb8-842cc547cfec.png)
![bildschirmfoto 2015-04-28 um 14 02 46](https://cloud.githubusercontent.com/assets/8446502/7369177/cee0eb36-edaf-11e4-8516-3e25ecb88a04.png)
![bildschirmfoto 2015-04-28 um 14 03 23](https://cloud.githubusercontent.com/assets/8446502/7369176/cee007f2-edaf-11e4-93fe-120b22d731c7.png)

**Comment by alexander-schranz** [comment]
as discussed with @c00n84 and @chirimoya I will allow to configurate CKEditor settings in the XML Template

Additional:  
if we support in the future other text_editor we should collect the parameters which are only for the ckeditor to add an abstraction layer for all parameters make it very unflexible. So if add a new editor we can e.g. add `tinymce_config` parameter collection then which contain all tinymce params.

e.g. ckeditor params:

``` xml
<param name="ckeditor_config" type="collection">
    <param name="allow_content" value"img[*](*) a[*](*) script[*](*) iframe[*](*) span[*](*)"/>
    <param name="style_set" value"[{name: 'CSS Style', element: 'span', attributes: { 'class': 'my_style'}]"/>
</param>
```

**Comment by danrot** [comment]
I would not distinguish between different implementations of text editors, I would prefer to have a single `allow_content` for all different text editors, and the content is responsible to translate that to the correct setting for the given text editor. This could be implemented as different strategies in the content type.

My main point is that I don't want to change too much in the templates, just because we are switching from ckeditor to tinymce.
