### ISSUE TITLE
I want to view documents (pdf) in the browser instead of downloading them

### ISSUE THREAD

**Issue by c00n84** [sulu-io/sulu#1125]
Currently the documents are downloaded via a download action. I think we can create a view action or something like this to open documents in the browser (e.g. PDF).

**Comment by wachterjohannes** [comment]
we only have to set `Content-Disposition` (here https://github.com/sulu-io/sulu/blob/b64cad45f02e4f72fb1a996d379961e2c433ede1/src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php#L118) to `inline` instead of `attachment` the question is should there be an own action or with a query parameter like `?inline` ?

**Comment by thomasduenser** [comment]
I've talked to @alexander-schranz about the problem and we think that the solution with a query parameter ```inline=1``` is enough and an own action isn't necessary.
https://github.com/sulu-io/sulu/pull/1134
