### ISSUE TITLE
Single internal links in snippets

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1681]
I try to have snippets including a single internal link. This does not work, because a snippet does not have a `workspaceKey` which is needed to have a working node API get route for the value of the single internal link.

Okay, this sounds confusing I think. Some code extracts which are important here:
- The url `/admin/api/nodes{/uuid}` requires a `workspaceKey`: https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Controller/NodeController.php#L132
- But the `workspaceKey` is optional for `single_internal_link`s: https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/single_internal_link.html.twig#L10

Inside the snippet template, the `workspaceKey` variable is `null` because, like I said, a snippet is not linked to a specific workspace (in my understanding of snippets).

However when:

1. using the `single_internal_link` content type inside a snippet and
2. selecting a page in the column navigation overlay and
3. coming back to the snippet form results in
4. a failing XHR request (e.g. `/admin/api/nodes/a000a259-c7cd-4ae9-9cc0-0fb2b8565592?depth=1&language=de&webspace-node=true`) – no `workspaceKey`

I would like to make a PR for this but I'm not sure were to get the `workspaceKey` from? Maybe you can give me a hint?

Thanks in advance.

**Comment by lennerd** [comment]
The `internal_links` content type is working fine inside snippets.

**Comment by danrot** [comment]
Actually you would have to make that work without the webspace, since you really have no webspace for a snippet (they are shared across all webspaces).

You should have a look at the `internal_links` content type. If you check the overlay there, you'll see that the first column shows the webspaces. So you can assign links from all the webspaces, which should also be the case for the `single_internal_link` type.
