### ISSUE TITLE
Properties without locale in database

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-io/sulu#1704]
I have a lot of pages with properties (in phpcr) which have a name like this: `i18n:-excerpt-title` i think it only happens with extensions but i am not quite sure.

**Comment by danrot** [comment]
We are running into the same issues as we already had, and I could imagine it is caused by this bug:

![image](https://cloud.githubusercontent.com/assets/405874/10903054/e41eb29a-8205-11e5-99fd-a637bf7f22b3.png)

@wachterjohannes I've thought we've already fixed that, but lets check again after this bug has been fixed. It also caused a strange issue when deleting a page, it probably doesn't make sense to research this issue before separately.

**Comment by wachterjohannes** [comment]
hmm perhaps the "undefined" thing was caused by multiple issues ... but i have fixed it here https://github.com/sulu-io/sulu-document-manager/pull/43

**Comment by wachterjohannes** [comment]
i cannot find the leak for this issue but i have fixed (hopefully finally) the undefined title issue!
