### ISSUE TITLE
Media selection: Image titles should be displayed in the content language instead of the user language

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu#1896]
![bildschirmfoto 2015-12-18 um 10 57 48](https://cloud.githubusercontent.com/assets/5627878/11894288/81dac076-a576-11e5-8539-fc152c0b2f0a.png)

The image titles are shown in English (=user language) although the current content language is German and the titles would be available in German. This could be confusing for e.g. Korean content administrators as they have no possibility to see the Korean titles when selecting the images.

@danrot: I discussed this with @berndhep, he also thinks that this should be changed.

**Comment by danrot** [comment]
I've already changed the language for the images in the overlay and in the list mentioned above.

A question still open to me is if we should also use the content language instead of the user language for the collections in the overlay (see the following screen).

![image](https://cloud.githubusercontent.com/assets/405874/13773259/a70e111a-ea98-11e5-9acb-cef73f14a9ad.png)

**Comment by danrot** [comment]
After a discussion with @berndhep we decided that the left handside collection navigation in the overlay should be using the system language of the user.

Additionally the title in the content type itself and in the overlay should append the content language (in brackets with the shadow page icon), if the shown language is a fallback.
