### ISSUE TITLE
Error message: public.server_error 200

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#720]
The javascript which parses the 500 exceptions from the backoffice does not deal with HTML exceptions properly, causing this error.

**Comment by danrot** [comment]
How can that be reproduced? Doesn't make any sense to me.

**Comment by dantleech** [comment]
Well, I think we need to improve that error handler generally, but in some cases the server returns invalid JSON (e.g. HTML) and that causes an "error" 200 to show.

An unrelated improvement would be to have an option to show, in dev mode, the returned response in a popup (either as JSON or HTML).

**Comment by danrot** [comment]
I would say a popup is just annoying, you could read the data also in the logs.

**Comment by wachterjohannes** [comment]
@dantleech i think for that we have the cool symfony toolbar for the ajax request since 2.6 (=

**Comment by thomasduenser** [comment]
I've updated to SULU 0.17.0 and everytime I changed something on the startpage (without saving) it threw the public server error 200.

When I looked into the Network tab (DevTools) the response wasn't correct (always containing "null" and there it stopped) -> the reason was a Twig Variable I was using in the templates but defined in the master.html.twig.

![bildschirmfoto 2015-04-22 um 09 01 41](https://cloud.githubusercontent.com/assets/3875917/7268924/93c29c10-e8ce-11e4-8cf7-5520dded36e0.png)

Once I've replaced the variable in the templates it then worked fine and the preview was correct. The response code was always 200...

![bildschirmfoto 2015-04-22 um 09 00 24](https://cloud.githubusercontent.com/assets/3875917/7268934/ab03851a-e8ce-11e4-915c-0d06a9c5edcf.png)

Hope this helps.

**Comment by danrot** [comment]
The error is appearing because the preview is rendering only a single block of the template, and it looks like variables from the outer scope are not available then.

Either we say we always render the entire page instead of only the content block. Then we can be sure that all variables are available, but the performance might be worse.

In addition we should maybe remove this general error handler displaying this label. And I still think this is strange that jquery handles a 200 as an error, nevermind what the content of the request is...
