### ISSUE TITLE
Accounts->Documents deleted documents are checked and added back 

### ISSUE THREAD

**Issue by xandrej** [sulu-io/sulu#898]
Go to:

- Accounts
- Choose a company for edit
- Go to Documents
- Add some documents and confirm
- Delete some documents
- Go back to to add (+), the deleted documents are checked, if you confirm again they are 
added back

Does not work by Snippets also, or wherever this form is.

**Comment by chirimoya** [comment]
please english, thx

**Comment by wachterjohannes** [comment]
@xandrej this is not in the standard anymore ... we should move this issue to the private repository /cc @danrot what do you think?

**Comment by danrot** [comment]
Well, I would say we should solve this issue for snippets, internal links and so on, as he describes it's also not working there.

**Comment by wachterjohannes** [comment]
ah ok sorry (= i have overread this!

**Comment by danrot** [comment]
The removeHandler of each of this itembox based component should be responsible for correcting the displayed data (since any of these components has its own representation it's not possible to fix this in a generic way).

* The internal links use a column-navigation, where the marked entries can't be reset from the outside.
* The media type works as expected in the Content section, for some reason it does not work in the contacts
* The snippets use a datagrid, which also has no possibility to unset data

**Comment by danrot** [comment]
Fixed the media type in the contact section in https://github.com/sulu-io/sulu/pull/1250
